default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  reconnect: false
  database: 'Hearim_development_master'
  username: 'root'
  password: <%= ENV['DB_PASSWORD'] %>
  host: 'localhost'

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  database: 'Hearim_production_master'